language: cpp
script: make unit
dist: trusty

before_install:
  - eval "${MATRIX_EVAL}"

matrix:
  include:
    - os: linux
      name: R Package

      dist: xenial
      language: r
      r: devel

      install:
        - R CMD build .
        - R CMD INSTALL miniparquet_*.tar.gz

      script:
        - (cd tests && R -f testthat.R)

    - os: osx
      osx_image: xcode11
      name: R Package

      language: r
      #r: devel

      install:
        - R CMD build .
        - R CMD INSTALL --build miniparquet_*.tar.gz
        - R CMD INSTALL miniparquet_*.tgz

      script:
        - (cd tests && R -f testthat.R)


    - os: windows
      name: R Package
      filter_secrets: false

      language: cpp

      before_script:
        - choco install r.project -y --version 3.6.0
        - wget "https://github.com/hannesmuehleisen/choco-rtools/raw/master/rtools.3.5.0.nupkg"
        - choco install rtools -s rtools.3.5.0.nupkg -f -y
        - choco install curl -y --force

      script:
        - export "PATH=/c/Rtools/bin:$PATH"
        - C:/Program\ Files/R/R-3.6.0/bin/R.exe CMD build .
        - C:/Program\ Files/R/R-3.6.0/bin/R.exe CMD INSTALL --build miniparquet_*.tar.gz
        - C:/Program\ Files/R/R-3.6.0/bin/R.exe CMD INSTALL miniparquet_*.zip
        - (cd tests; C:/Program\ Files/R/R-3.6.0/bin/R.exe -f testthat.R)


